### ISSUE TITLE
Extension not found under linux extensions tab

### ISSUE THREAD

**Issue by Panke** [microsoft/vscode-azurecli#75] opened 2020-10-27 07:25 UTC
Neither can I install the extension via `ext install ms-vscode.azurecli` nor can I find it manually in the market place. 

I am running
> Version: 1.50.1
> Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
> Date: 2020-10-15T10:42:48.064Z
> Electron: 9.3.2
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Linux x64 5.9.1-arch1-1

How do I install it?

**Comment by chrmarti** [comment] 2020-10-27 07:30
Do you see other extensions in the Extensions viewlet? Are you behind a network proxy?

**Comment by Panke** [comment] 2020-10-27 07:33
Yes, `Azure App Service`, `Azure Storage`, `Azure Event Grid` are there as are many others (language packs, keymaps etc.) No Proxy.

**Comment by chrmarti** [comment] 2020-10-27 09:03
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed by chrmarti** 2020-10-27 09:03 UTC
Labels: needs more info
