### ISSUE TITLE
'az' not found on PATH, make sure it is installed.

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/vscode-azurecli#12] opened 2017-06-13 18:36 UTC
OS: OSX 10.12.5
VSCode: Version 1.13.0 (1.13.0)
Azure CLI: azure-cli (2.0.7)
Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/rspaulino/lib/azure-cli/bin/python'
------------------------------------------------------------
I'm able to run az from the terminal and from vscode when I send the command to the terminal but when I open vscode and open a file with extension .azcli I get the following error 'az' not found on PATH, make sure it is installed. 

And the intellisense doesn't come up.

**Comment by rspaulino** [comment] 2017-06-13 18:51
Uninstalling and Installing the extension back again fix the issue.

**Comment by chrmarti** [comment] 2017-06-13 19:32
Did you install az after installing the extension? Maybe the extension's PATH hadn't picked up the new location yet. Not sure how reinstalling would help except that VSCode would reload with the latest PATH.

**Comment by rspaulino** [comment] 2017-06-13 21:44
I have az install already but it wasn't working so I delete it and install it multiple times and that didn't help, so I download your code from GitHub and ran it on vscode and that was working I don't know if it's because I have the SYNC extension and the sync extension was the one that install vscode-azurecli on my second Mac.

**Comment by chrmarti** [comment] 2018-03-12 09:00
Closing as we don't have enough information to address the cause.

**Closed by chrmarti** 2018-03-12 09:00 UTC
