### ISSUE TITLE
No completions on az webapp browse --name

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#21] opened 2017-09-13 20:58 UTC
``` console
az login
az account list -o table
az group create --name testazcli-rg --location westus
az appservice plan create --name testazcli-name --resource-group testazcli-rg --location westus --sku FREE 
az webapp create --name cdias-testazcli-site --plan testazcli-name --resource-group testazcli-rg
```

Now try to write the browse command:

``` console
az webapp browse --name 
```

result: no completions for name (I pressed ctrl+space to try to bring up completions):

![image](https://user-images.githubusercontent.com/1487073/30400381-92d65f8e-988b-11e7-9bae-22a7f068a8d5.png)

**Comment by chrmarti** [comment] 2017-09-25 20:52
Duplicate of #20

**Closed by chrmarti** 2017-09-25 20:52 UTC
